[package]
name = "tonic-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.1", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }
tonic = "0.8"
prost = "0.11"

[build-dependencies]
tonic-build = { version = "0.8.0", features = ["prost"] }
